### (price api)
GET https://api.coindesk.com/v1/bpi/currentprice.json

### (weather api)
GET https://free-api.heweather.com/v5/weather?key=987bc68871c94142ae815b39a1081e63&city=chengdu

### (price api)
GET https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=297fbec3-e209-40f1-9efa-1a067af4e3fe&start=1&limit=4&convert=CNY